openapi: '3.0.3'
info:
  title: 'Final Project Alta: Barengin'
  version: '1.0'
  description: 'API Documentation for Barengin'
  contact: 
    name: Barengin Official
    url: https://barengin.site
    email: sahrilmahendra@gmail.com
externalDocs: 
  description: "GitHub Repository of Final Project: Barengin"
  url: https://github.com/project-capstone
servers:
  - url: https://barengin.site
    description: Base URL that will be used for endpoints
tags:
  - name: Authentication
    description: Endpoint for verifying who a user is
  - name: Sign Up
    description: Endpoint for user registration
  - name: Users
    description: Endpoint for perform operations on user
  - name: Products
    description: Endpoint for perform operations on product
  - name: Group Products
    description: Endpoint for perform operations on group product
  - name: Orders
    description: Endpoint for perform operations on order
paths:
####################################
#  AUTHENTICATION
####################################
  /login:
    post:
      tags:
        - Authentication
      summary: Get token for access to account
      requestBody:
        $ref: '#/components/requestBodies/requestBodyLogin'
      responses:
        '200':
          $ref: '#/components/responses/loginSuccess'
        '400':
          $ref: '#/components/responses/loginFailed'
####################################
#  SIGN UP
####################################
  /signup:
    post:
      tags:
        - Sign Up
      summary: Create a new account for customer
      requestBody:
        $ref: '#/components/requestBodies/requestBodyUser'
      responses:
        '200':
          $ref: '#/components/responses/successOperationNonData'
        '400':
          $ref: '#/components/responses/createUserFailed'
####################################
#  USERS
####################################
  /users:
    get:
      tags:
        - Users
      summary: Get all customer's data for admin
      security:
        - JWTAuth: []
      responses:
        '200':
          $ref: '#/components/responses/getAllUsersSuccess'
        '400':
          $ref: '#/components/responses/getAllUsersFailed'
  /users/{id}:
    get:
      tags:
        - Users
      summary: Get customer's data by id
      security:
        - JWTAuth: []
      parameters:
        - $ref: '#/components/parameters/idParam'
      responses:
        '200':
          $ref: '#/components/responses/getUserSuccess'
        '400':
          $ref: '#/components/responses/getUserFailed'
    put:
      tags:
        - Users
      summary: Update customer's data by id
      security:
        - JWTAuth: []
      parameters:
        - $ref: '#/components/parameters/idParam'
      requestBody:
        $ref: '#/components/requestBodies/requestBodyUserUpdate'
      responses:
        '200':
          $ref: '#/components/responses/successOperationNonData'
        '400':
          $ref: '#/components/responses/updateUserFailed'
    delete:
      tags:
        - Users
      summary: Delete customer's data by id
      security:
        - JWTAuth: []
      parameters:
        - $ref: '#/components/parameters/idParam'
      responses:
        '200':
          $ref: '#/components/responses/successOperationNonData'
        '400':
          $ref: '#/components/responses/deleteUserFailed'
####################################
####################################
#  COMPONENTS
####################################
components:
  schemas:
    requestDataLogin:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    requestDataUser:
      type: object
      required:
        - name
        - email
        - password
        - phone
      properties:
        name:
          type: string
        email:
          type: string
          format: email
          description: inputted email must be unique
        password:
          type: string
          minLength: 6
        phone:
          type: string
          format: e164
          description: inputted phone number must be unique
    requestDataProduct:
      type: object
      required:
        - name_product
        - detail_product
        - price
        - photo
        - limit
      properties:
        name_product:
          type: string
        detail_product:
          type: string
        price:
          type: integer
          minimum: 1
        photo:
          type: string
        limit:
          type: integer
    requestDataGroupProduct:
      type: object
      required:
      - id_product
      properties:
        id_product:
          type: integer
    requestDataOrder:
      type: object
      properties:
        order: 
          type: object
          properties:
            id_group_product: 
              type: integer
        credit_card:
          type: object
          properties:
            typ:
              type: string
            name:
              type: string
            number:
              type: string
            cvv:
              type: integer
            month:
              type: integer
            year:
              type: integer
    requestDataOrderUpdate:
      type: object
      properties:
        credential:
          type: string
    responseLoginWithData:
      type: object
      properties:
        Code:
          type: integer
        Message:
          type: string
        Data:
          type: object
          properties:
            ID:
              type: integer
            Name:
              type: string
            Token:
              type: string
            Role: 
              type: string
    responseUserWithData:
      type: object
      properties:
        Code:
          type: integer
        Message:
          type: string
        Data:
          type: object
          properties:
            ID:
              type: integer
            Name:
              type: string
            Email:
              type: string
            Phone:
              type: string
    responseUserWithDataArray:
      type: object
      properties:
        Code:
          type: integer  
        Message:
          type: string
        Data:
          type: array
          items:
            type: object
            properties:
              ID:
                type: integer
              Name:
                type: string
              Email:
                type: string
              Phone:
                type: string    
    responseProductWithData:
      type: object
      properties:
        Code:
          type: integer
        Message:
          type: string
        Data:
          type: object
          properties:
            ID:
              type: integer
            NameProduct:
              type: string
            DetailProduct:
              type: string
            Price:
              type: integer
              minimum: 1
            Photo:
              type: string
            Limit:
              type: integer
    responseProductWithDataArray:
      type: array
      items:
        type: object
        properties:
          Code:
            type: integer
          Message:
            type: string
          Data:
            type: object
            properties:
              ID:
                type: integer
              NameProduct:
                type: string
              DetailProduct:
                type: string
              Price:
                type: integer
                minimum: 1
              Photo:
                type: string
              Limit:
                type: integer
    responseGroupProductWithData:
      type: object
      properties:
        Code:
          type: integer
        Message:
          type: string
        Data:
          type: object
          properties:
            ID:
              type: integer
            UsersID:
              type: integer
            ProductID:
              type: integer
            NameGroupProduct:
              type: string
            CapacityGroupProduct:
              type: integer
            AdminFee:
              type: integer
            TotalPrice:
              type: integer 
            Duration:
              type: string
    responseGroupProductWithDataArray:
      type: array
      items:
        type: object
        properties:
          Code:
            type: integer
          Message:
            type: string
          Data:
            type: object
            properties:
              ID:
                type: integer
              UsersID:
                type: integer
              ProductID:
                type: integer
              NameGroupProduct:
                type: string
              CapacityGroupProduct:
                type: integer
              AdminFee:
                type: integer
              TotalPrice:
                type: integer 
              Duration:
                type: string
    responseOrderWithData:
      type: object
      properties:
        order: 
          type: object
          properties:
            ID:
              type: integer
            ID_User:
              type: integer
            ID_Group_Product:
              type: integer
            Price_Pemesanan:
              type: integer
            credential:
              type: string
    responseOrderGroupProductWithDataArray:
      type: object
      properties:
        order: 
          type: object
          properties:
            ID:
              type: integer
            ID_User:
              type: integer
            ID_Group_Product:
              type: integer
            Price_Pemesanan:
              type: integer
    responseOrderWithDataArray:
      type: array
      items:
        type: object
        properties:
          order: 
            type: object
            properties:
              ID:
                type: integer
              UserID:
                type: integer
              GroupProductID:
                type: integer
              PriceOrder:
                type: integer
              credential:
                type: string
    responseNonData: 
      type: object
      properties:
        Code:
          type: integer
        Message:
          type: string 
  parameters:
    idParam:
      name: id
      in: path
      required: true
      schema:
        type: integer
        example: 1
    availParam:
      name: available
      in: path
      required: true
      schema:
        type: string
        example: available
  securitySchemes:
    JWTAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "use Token"  
  requestBodies:
    requestBodyLogin:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/requestDataLogin'
          examples:
            user1:
              value:
                email: admin@admin.com
                password: admin123
            user2:
              value:
                email: s@g.sb
                password: asd!@#1
            user3:
              value:
                email: nurilhuda7337@gmail.com
                password: "12345678"
    requestBodyUser:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/requestDataUser'
          examples:
            newUser1:
              value:
                name: Nuril Huda
                email: nurilhuda7337@gmail.com
                password: "12345678"
                phone: "+6281234567890"
            newUser2:
              value:
                name: Supriadi
                email: s@g.sb
                password: asd!@#12
                phone_number: "+67712345"
            newUser3:
              value:
                name: Sahril Mahendra
                email: sahrilmahendra@gmail.com
                password: qwertyui
                phone: "+62899999999999"
    requestBodyUserUpdate:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/requestDataUser'
          examples:
            newData1:
              value:
                name: Supriadi Baru
                email: new.s@yahoo.co.id
                password: newpass
                phone: "+628966066096"
    requestBodyProduct:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/requestDataProduct'
          examples:
            product1:
              value:
                name_product: Netflix
                detail_product: Langganan Netflix untuk 1 bulan
                price: 200000
                photo: logo-netflix-upload-file-2021-12-12T07:19:15.jpeg
                limit: 4
            product2:
              value:
                name_product: Spotify
                detail_product: Langganan Spotify untuk 1 bulan
                price: 100000
                photo: logo-spotify-upload-file-2021-12-12T12:12:12.jpeg
                limit: 5
    requestBodyProductUpdate:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/requestDataProduct'
          examples:
            product1:
              value:
                name_product: Netflix Super Premium
                detail_product: Langganan Netflix SP untuk 1 bulan
                price: 350000
                photo: logo-netflix-upload-file-2021-12-12T07:19:15.jpeg
                limit: 4
    requestBodyGroupProduct:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/requestDataGroupProduct'
          examples:
            group1:
              value:
                id_product: 1
            group2:
              value:
                id_product: 2
    requestBodyGroupProductUpdate:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/requestDataGroupProduct'
          examples:
            group1:
              value:
                id_product: 3
    requestBodyOrder: 
      required: true
      content:
        application/json:
          schema:  
            $ref: '#/components/schemas/requestDataOrder'
          example:
            order:
              id_group_product: 1
            credit_card:
              typ: Visa
              name: Supriadi
              number: 1234-1234-1234-1234
              cvv: 234
              month: 12
              year: 21
    requestBodyOrderUpdate: 
      required: true
      content:
        application/json:
          schema:  
            $ref: '#/components/schemas/requestDataOrderUpdate'
          example:
            credential:
              email: subs.netflix@mail.com
              password: qwertyui
  responses:
    loginSuccess:
      description: Success Response Data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseLoginWithData'
          examples:
            Admin:
              value:
                Code: 200
                Message: Login Success
                Data: {
                  ID: 1,
                  Name: Admin,
                  Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MzgxOTUwMDksInVzZXJJZCI6MX0.0gso_gffYqaDGmCTqYClvhaNZZdbe7FbV7hJ02lOpoQ,
                  Role: admin
                }
            Customer:
              value:
                Code: 200
                Message: Login Success
                Data: {
                  ID: 3,
                  Name: Supriadi,
                  Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MzgxOTUwMDksInVzZXJJZCI6MX0.0gso_gffYqaDGmCTqYClvhaNZZdbe7FbV7hJ02lOpoQ,
                  Role: customer
                }
    loginFailed:
      description: Bad Request Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseNonData'
          example:
            Code: 400 
            Message: Email or Password Incorrect
    successOperationNonData:
      description: Success Response Non Data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseNonData'
          example:
            Code: 200
            Message: Success Operation
    createUserFailed:
      description: Bad Request Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseNonData'
          examples:
            Invalid Name:
              $ref: '#/components/examples/invalidName'
            Invalid Email:
              $ref: '#/components/examples/invalidEmail'
            Invalid Password:
              $ref: '#/components/examples/invalidPassword'
            Password Must Consist Of:
              $ref: '#/components/examples/passwordMustConsistOf'
            Invalid Telephone Number:
              $ref: '#/components/examples/invalidTelephoneNumber'
            Bad Request:
              $ref: '#/components/examples/badRequest'
    getAllUsersSuccess:
      description: Success Response Data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseUserWithDataArray'
          example:
            Code: 200
            Message: Success Operation
            Data: [{
              ID: 2,
              Name: Nuril Huda,
              Email: nurilhuda7337@gmail.com,
              Phone: "+6281234567890"
              },
              {
              ID: 3,
              Name: Supriadi,
              Email: s@g.sb,
              Phone: "+67712345890"
              },
              {
              ID: 4,
              Name: Sahril Mahendra,
              Email: sahrilmahendra@gmail.com,
              Phone: "+62899999999999"
              }]
    getAllUsersFailed:
      description: Bad Request Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseNonData'
          examples:
            Data Not Found:
              $ref: '#/components/examples/dataNotFound'
            Bad Request:
              $ref: '#/components/examples/badRequest'
    getUserSuccess:
      description: Success Response Data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseUserWithData'
          example:
            Code: 200
            Message: Success Operation
            Data: {
              ID: 1,
              Name: Nuril Huda,
              Email: nurilhuda7337@gmail.com,
              Phone: "+6281234567890"
            }
    getUserFailed:
      description: Bad Request Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseNonData'
          examples:
            Invalid Id:
              $ref: '#/components/examples/invalidId'
            Data Not Found:
              $ref: '#/components/examples/dataNotFound'
            Bad Request:
              $ref: '#/components/examples/badRequest'
    updateUserFailed:
      description: Bad Request Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseNonData'
          examples:
            Invalid Id:
              $ref: '#/components/examples/invalidId'
            Data Not Found:
              $ref: '#/components/examples/dataNotFound'
            Access Forbidden:
                $ref: '#/components/examples/accessForbidden'
            Invalid Name:
              $ref: '#/components/examples/invalidName'
            Invalid Email:
              $ref: '#/components/examples/invalidEmail'
            Invalid Password:
              $ref: '#/components/examples/invalidPassword'
            Password Must Consist Of:
              $ref: '#/components/examples/passwordMustConsistOf'
            Invalid Telephone Number:
              $ref: '#/components/examples/invalidTelephoneNumber'
            Bad Request:
              $ref: '#/components/examples/badRequest'
    deleteUserFailed:
      description: Bad Request Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseNonData'
          examples:
            Invalid Id:
              $ref: '#/components/examples/invalidId'
            Data Not Found:
              $ref: '#/components/examples/dataNotFound'
            Access Forbidden:
                $ref: '#/components/examples/accessForbidden'
    createProductFailed:
      description: Bad Request Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseNonData'
          examples:
            File Extension Not Allowed:
              $ref: '#/components/examples/fileExtensionNotAllowed'
            Illegal File:
              $ref: '#/components/examples/illegalFile'
            Size File Too Big:
              $ref: '#/components/examples/sizeFileTooBig'
            Bad Request:
              $ref: '#/components/examples/badRequest'
    productServerFailed:
      description: Internal Server Error Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseNonData'
          examples:
            Can't Connect to Server:
              $ref: '#/components/examples/cantConnecttoServer'
            Failed to Upload File:
              $ref: '#/components/examples/failedtoUploadFile'
    getAllProductsSuccess:
      description: Success Response Data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseProductWithDataArray'
          example:
            Code: 200
            Message: Success Operation
            Data: [{ 
                ID: 1,
                NameProduct: Netflix,
                DetailProduct: Langganan Netflix untuk 1 bulan,
                Price: 200000,
                Photo: logo-netflix-upload-file-2021-12-12T07:19:15.jpeg,
                Limit: 4
                },
                { 
                ID: 2,
                NameProduct: Spotify,
                DetailProduct: Langganan Spotify untuk 1 bulan,
                Price: 100000,
                Photo: logo-spotify-upload-file-2021-12-12T12:12:12.jpeg,
                Limit: 5
                }]
    getAllProductsFailed:
      description: Bad Request Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseNonData'
          examples:
            Data Not Found:
              $ref: '#/components/examples/dataNotFound'
            Bad Request:
              $ref: '#/components/examples/badRequest'
    getProductSuccess:
      description: Success Response Data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseProductWithData'
          example:
            Code: 200
            Message: Success Operation
            Data: { 
                ID: 3,
                NameProduct: Gramedia,
                DetailProduct: Langganan Gramedia untuk 1 bulan,
                Price: 150000,
                Photo: logo-gramedia-upload-file-2021-12-12T12:12:12.jpeg,
                Limit: 3
                }
    getProductFailed:
      description: Bad Request Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseNonData'
          examples:
            Invalid Id:
              $ref: '#/components/examples/invalidId'
            Data Not Found:
              $ref: '#/components/examples/dataNotFound'
            Bad Request:
              $ref: '#/components/examples/badRequest'
    updateProductFailed:
      description: Bad Request Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseNonData'
          examples:
            Invalid Id:
              $ref: '#/components/examples/invalidId'
            Data Not Found:
              $ref: '#/components/examples/dataNotFound'
            Access Forbidden:
              $ref: '#/components/examples/accessForbidden'
            Bad Request:
              $ref: '#/components/examples/badRequest'
            File Extension Not Allowed:
              $ref: '#/components/examples/fileExtensionNotAllowed'
            Illegal File:
              $ref: '#/components/examples/illegalFile'
            Size File Too Big:
              $ref: '#/components/examples/sizeFileTooBig'
    deleteProductFailed:
      description: Bad Request Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseNonData'
          examples:
            Invalid Id:
              $ref: '#/components/examples/invalidId'
            Data Not Found:
              $ref: '#/components/examples/dataNotFound'
            Access Forbidden:
              $ref: '#/components/examples/accessForbidden'
    createGroupProductFailed:
      description: Bad Request Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseNonData'
          examples:
            Bad Request:
              $ref: '#/components/examples/badRequest'
    getAllGroupProductsSuccess:
      description: Success Response Data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseGroupProductWithDataArray'
          example:
            Code: 200
            Message: Success Operation
            Data: [{ 
                ID: 1,
                UsersID: 5,
                ProductID: 2, 
                NameGroupProduct: Group Product 1,
                CapacityGroupProduct: 5,
                AdminFee: 6500,
                TotalPrice: 26500,
                Duration: 1-12-2021
                },
                { 
                ID: 2,
                UsersID: 12,
                ProductID: 1, 
                NameGroupProduct: Group Product 2,
                CapacityGroupProduct: 4,
                AdminFee: 6500,
                TotalPrice: 56500,
                Duration: 1-12-2021
                }]
    getAllGroupProductsFailed:
      description: Bad Request Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseNonData'
          examples:
            Data Not Found:
              $ref: '#/components/examples/dataNotFound'
            Bad Request:
              $ref: '#/components/examples/badRequest'
    getAllGroupProductsAvailableSuccess:
      description: Success Response Data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseGroupProductWithDataArray'
          example:
            Code: 200
            Message: Success Operation
            Data: [{ 
                ID: 1,
                UsersID: 5,
                ProductID: 2, 
                NameGroupProduct: Group Product 1,
                CapacityGroupProduct: 5,
                AdminFee: 6500,
                TotalPrice: 26500,
                Duration: 1-12-2021
                },
                { 
                ID: 2,
                UsersID: 12,
                ProductID: 1, 
                NameGroupProduct: Group Product 2,
                CapacityGroupProduct: 4,
                AdminFee: 6500,
                TotalPrice: 56500,
                Duration: 1-12-2021
                }]
    getAllGroupProductsAvailableFailed:
      description: Bad Request Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseNonData'
          examples:
            Data Not Found:
              $ref: '#/components/examples/dataNotFound'
            Bad Request:
              $ref: '#/components/examples/badRequest'
    getGroupProductSuccess:
      description: Success Response Data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseGroupProductWithData'
          example:
            Code: 200
            Message: Success Operation
            Data: { 
                ID: 2,
                UsersID: 12,
                ProductID: 1, 
                NameGroupProduct: Group Product 2,
                CapacityGroupProduct: 4,
                AdminFee: 6500,
                TotalPrice: 56500,
                Duration: 1-12-2021
                }
    getGroupProductFailed:
      description: Bad Request Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseNonData'
          examples:
            Invalid Id:
              $ref: '#/components/examples/invalidId'
            Data Not Found:
              $ref: '#/components/examples/dataNotFound'
            Bad Request:
              $ref: '#/components/examples/badRequest'
    updateGroupProductFailed:
      description: Bad Request Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseNonData'
          examples:
            Invalid Id:
              $ref: '#/components/examples/invalidId'
            Data Not Found:
              $ref: '#/components/examples/dataNotFound'
            Access Forbidden:
              $ref: '#/components/examples/accessForbidden'
            Bad Request:
              $ref: '#/components/examples/badRequest'
    deleteGroupProductFailed:
      description: Bad Request Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseNonData'
          examples:
            Invalid Id:
              $ref: '#/components/examples/invalidId'
            Data Not Found:
              $ref: '#/components/examples/dataNotFound'
            Access Forbidden:
              $ref: '#/components/examples/accessForbidden'
    createOrderFailed:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseNonData'
          examples:
            Data Not Found:
              $ref: '#/components/examples/dataNotFound'
            Access Forbidden:
              $ref: '#/components/examples/accessForbidden'
            Bad Request:
              $ref: '#/components/examples/badRequest'
    getAllOrdersSuccess:
      description: Success Operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseOrderWithDataArray'
          example:
            Code: 200
            Message: Success Operation
            Data: [{
              ID: 1,
              UserID: 2,
              GroupProductID: 1,
              PriceOrder: 24500,
              credential: ""
              },
              {
              ID: 2,
              UserID: 2,
              GroupProductID: 2,
              PriceOrder: 54500,
              credential: ""
              }            
            ]
    getAllOrdersFailed:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseNonData'
          examples:
            Bad Request:
              $ref: '#/components/examples/badRequest'
            Data Not Found:
              $ref: '#/components/examples/dataNotFound'
  examples:
    accessForbidden:
      value:
        Code: 400
        Message: Access Forbidden                
    badRequest:
      value:
        Code: 400
        Message: Bad Request
    cantConnecttoServer:
      value:
        Code: 500
        Message: Can't Connect to server
    dataisAvailable:
      value:
        Code: 400
        Message: Data is Available
    dataNotFound:
      value:
        Code: 400
        Message: Data Not Found
    failedtoUploadFile:
      value:
        Code: 500
        Message: Failed to Upload File
    fileExtensionNotAllowed:
      value:
        Code: 400
        Message: File Extension Not Allowed
    illegalFile:
      value:
        Code: 400
        Message: Illegal File
    invalidEmail:
      value:
        Code: 400
        Message: Invalid Email
    invalidId:
      value:
        Code: 400
        Message: Invalid Id
    invalidName:
      value:
        Code: 400
        Message: Invalid Name
    invalidPassword:
      value:
        Code: 400
        Message: Invalid Password
    invalidTelephoneNumber:
      value:
        Code: 400
        Message: Invalid Telephone Number
    notAvailable:
      value:
        Code: 400
        Message: Not Available
    passwordMustConsistOf:
      value:
        Code: 400
        Message: Password must consist of 6 characters or more
    sizeFileTooBig:
      value:
        Code: 400
        Message: Size File Too Big
    